# Generated by Django 2.0.3 on 2018-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True),
        ),
    ]
